### ISSUE TITLE
Modconflict? Easy dev controls

### ISSUE THREAD

**Issue by noahluth** [GtX-Andy/easyDevelopmentControls#11]
Hey when I want to launch the game the easy development controls dont appears... I think somekind of mod conflict... do you have any idea? I have around 700 and I don't want to sort it out by hand😂

**Comment by GtX-Andy** [comment]
Easy Development Controls requires Game Version: 1.4.1.0 this would be the first thing to check if you do not see it load. 😉 
If it showing as loaded in your log file then you could check the 'Input Binding' does not conflict.

**Comment by noahluth** [comment]
Error unsupported mod discription said in the log

**Comment by GtX-Andy** [comment]
yes this is because your current game version is below that which is required by EDC.

Game Version: 1.4.1.0 is required for Easy Development Controls V1.0.0.0 as a minimum ;-)

Any time you see ***Error unsupported mod description*** for a mod this generally means it requires a newer version of the game or you are using a mod from a different game version such as FS17 mod in FS22 without correctly converting it 😁
