### ISSUE TITLE
Wear and dirt condition not applied to "multi mount" equipment ?

### ISSUE THREAD

**Issue by Szmiti** [GtX-Andy/easyDevelopmentControls#33]
Hello,
Great mod - use it all the time now - only one small issue seen: in case of "multi mount" equipment (eg. Alpego RK300 + Jet-M drill combo) where not all attached directly to the tractor, then wear and dirt condition set through the vehicles sub-menu is only applied to the 'part' of the implement directly attached to the tractor - see pic (dirt and wear both set to 100%).

Game :1.6.0.0
Easy Dev Controls ver 1.2.0.0 (latest on modhub at date of writing)

Szmiti

![Alpego drill combi wear   dirt](https://user-images.githubusercontent.com/47475508/180782996-af2a1738-2b9e-40b6-813e-9dc1d0193d21.jpg)

**Comment by GtX-Andy** [comment]
Hi,
Sorry for the very delayed response.
I am glad to hear you enjoy the mod and find it helpful 😊 

I see what you mean regarding the `multi mount` equipment.. I will make some adjustments to this feature in the next update so this problem is fixed. thanks for the detailed information and image..

In the mean time if your not aware you can also adjust the dirt on a specific implement by looking at it when standing beside it. This may help especially if testing etc 😁
