### ISSUE TITLE
Admin rights in multiplayer are not enough to edit fields

### ISSUE THREAD

**Issue by carxonic-dev** [GtX-Andy/easyDevelopmentControls#44]
Hello,
yesterday I tried to edit the field of a fellow player as game admin. The fruit did not grow on the corresponding field. In single player I was able to edit the field as I wished without any problems. On the server, I had to join the appropriate farm before the server accepted the change.
If this is a feature, please close the task again. From the user's point of view, the issue feels like a bug.

Map GulliDeckels FS22_Departement_Haut_Beyleron.zip 0.8.1.0 Beta (DLC Platinum Expansion)

https://sharemods.com/qyi30xkjog0d/FS22_Departement_Haut_Beyleron.zip.html

The server log only said that the change could not be made.

**Comment by GtX-Andy** [comment]
Hi, Sorry for the delay in replying. 

This is actually how it is intended to work, I did this because it can be easy to make a mistake even as an admin.

By limiting to the farm the user is part of it also allows the `Set All Fields` feature to only be applied to users fields without accidently damaging the work of another farm.

The log print could possibly be adjusted to provide more information in the future.

Cheers 🍻
