### ISSUE TITLE
Fehler server 

### ISSUE THREAD

**Issue by Bandesss** [GtX-Andy/easyDevelopmentControls#46]
Hallo wir haben folgendes
Es kommt beim benutzen der Superkraft
https://github.com/Stephan-S/FS22_AutoDrive/files/10526133/log.txt

**Comment by Bandesss** [comment]
Wieder Fehler auch mit dem GitHub Versionsnummer

**Comment by GtX-Andy** [comment]
Hi,

I do not see any issues in the log.xml that would make me believe this issue is caused by Easy Development Controls.
I am actually not sure why someone from the 'AutoDrive GitHub' would suggest that this is the issue  🤔 

It also does not appear to be caused by Super Strength either as if this was enabled via EDC there would be a notification in the log file.

The error looks to be an issue with syncing an object such as a vehicle or a building. This could be caused by a faulty script in a vehicle or another global script for placeables or vehicles.

My recommendation would be to remove any mods you have added recently and see if the error is gone. You can also try disabling all vehicle script mods and enable them one at a time until you see the error again.

p.s The GitHub version is not the latest release. The latest release is available [Here](https://www.farming-simulator.com/mod.php?&mod_id=244313&title=fs2022)

Good luck with finding the issue :-)

**Comment by Bandesss** [comment]
Vielen dank für die info
