### ISSUE TITLE
[Object Storage]: Errors while using that mod

### ISSUE THREAD

**Issue by westor7** [GtX-Andy/easyDevelopmentControls#61]
Hello,

First of all sorry that i post that in this repo but you don't have any Object Storage repo so i can report it there.

While loading the game i am getting the following errors:

`2023-07-08 16:20 Error: spec type name 'objectStorageCapacity' is already in use!`

AND

`2023-07-08 16:20 ERROR: geometry 'occluderMeshShape_GtX' needs to be marked as an occluder by the editor; please load/save the I3D to flush the occluder shape flag to the geometry.`

Full log.txt: [log.txt](https://github.com/GtX-Andy/easyDevelopmentControls/files/11990749/log.txt)

- Thanks!

**Comment by GtX-Andy** [comment]
Hi 👋 

As you may be aware this was fixed in update 1.2.0.1 of Object Storage available [HERE](https://www.farming-simulator.com/mod.php?&mod_id=255609&title=fs2022)

Thank you for contacting me and reporting the issue, sometimes these appear when the game version is updated.
Depending on how busy I am with family and work I do not always see GitHub messages or forum messages but I do appreciate them.

If you need to report a bug you can also message me directly on the [Giants Official Forums](https://forum.giants-software.com/) as user **GtX** and I will reply when I am available.
