### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by wo140k-tech** [GtX-Andy/easyDevelopmentControls#63]
Hello, we encountered the following problem:
This cool mod also works on our server, and when we changed the rendering distance, we noticed that all players had DirectX 12 enabled. We tried to solve this problem by changing to DirectX 11, but now everyone’s FPS was lower by about 10-20 FPS. Can you please help us somehow?

Email - gabriel.golovetchii@gmail.com
![image](https://github.com/GtX-Andy/easyDevelopmentControls/assets/80915920/07a05210-0997-477c-8bf0-5ce9c294313f)
![image](https://github.com/GtX-Andy/easyDevelopmentControls/assets/80915920/777a739e-cff9-4b38-9cc5-a62a09667748)

Sincerely,
Gabriel

**Comment by GtX-Andy** [comment]
I am not sure what your issue is here, it does not sound like a problem with Easy Development Controls though 🤔 

If you are experiencing low frames or other graphic issues you can try deleting the 'shader_cache' folder located at **C:\Users\%USERNAME%\Documents\My Games\FarmingSimulator2022** and restarting your game.

You will notice some lag and low frames when you first enter the game and move around as the new cache files are created.
This method can also help after major game / map updates.

Good luck and I hope you get your issues sorted.
