### ISSUE TITLE
Flight permission?

### ISSUE THREAD

**Issue by oliver989** [GtX-Andy/easyDevelopmentControls#72]
Would it be possible to add flight permission also?
Then this would be a great tool for multiplayer admins.

**Comment by GtX-Andy** [comment]
I have not added permissions for the  flight function because it is also possible for any user to activate this via the console command  **gsPlayerFlightMode** so doing so would not stop those that wish to do it.

For a future release in the next game I could look at this as an option along with an option to disable the console command if it is viable.
